services:
  - type: web
    name: dss-video-games-api
    env: python
    region: singapore
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn api:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
